openapi: 3.0.1
info:
  title: User Service System API
  description: API documentation for a service for creating, retrieving, updating, and deleting users.
  version: 1.0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /api/v1/userservice/update:
    put:
      tags:
        - user-controller
      operationId: updateUser
      parameters:
        - name: email
          in: query
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        400:
          description: Bad Request
          content:
            '*/*':
              schema:
                type: string
        200:
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /api/v1/userservice/register:
    post:
      tags:
        - user-controller
      operationId: registerUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        400:
          description: Bad Request
          content:
            '*/*':
              schema:
                type: string
        200:
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /api/v1/userservice/user:
    get:
      tags:
        - user-controller
      operationId: getUserByEmail
      parameters:
        - name: email
          in: query
          required: true
          schema:
            type: string
      responses:
        400:
          description: Bad Request
          content:
            '*/*':
              schema:
                type: string
        200:
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/User'
  /api/v1/userservice/list:
    get:
      tags:
        - user-controller
      operationId: getUser
      responses:
        400:
          description: Bad Request
          content:
            '*/*':
              schema:
                type: string
        200:
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
  /api/v1/userservice/delete:
    delete:
      tags:
        - user-controller
      operationId: deleteUser
      requestBody:
        content:
          application/json:
            schema:
              type: string
      responses:
        400:
          description: Bad Request
          content:
            '*/*':
              schema:
                type: string
        200:
          description: OK
          content:
            '*/*':
              schema:
                type: string
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string
